# user_id -> list of 5 food interests (None means new user, no likes yet)
USER_INTERESTS = {
    "user_001": ["pizza", "pasta", "burgers", "sushi", "tacos"],
    "user_002": ["biryani", "curry", "dosa", "tandoori", "samosa"],
    "user_003": ["salad", "smoothie", "quinoa", "avocado", "granola"],
    "user_004": ["steak", "bbq", "ribs", "wings", "bacon"],
    "user_005": ["ramen", "sushi", "dumplings", "pho", "pad_thai"],
    "user_006": ["pizza", "wings", "nachos", "hotdog", "fries"],
    "user_007": ["idli", "dosa", "sambar", "rasam", "pongal"],
    "user_008": ["cheesecake", "brownie", "icecream", "waffle", "crepe"],
    "user_009": ["tacos", "burrito", "nachos", "quesadilla", "guacamole"],
    "user_010": ["sushi", "ramen", "tempura", "yakitori", "miso"],
    "user_011": ["butter_chicken", "biryani", "naan", "paneer", "lassi"],
    "user_012": ["avocado", "salad", "smoothie", "acai", "hummus"],
    "user_013": ["steak", "ribs", "pulled_pork", "bbq", "cornbread"],
    "user_014": ["pasta", "pizza", "risotto", "tiramisu", "bruschetta"],
    "user_015": ["pho", "banh_mi", "spring_rolls", "pad_thai", "laksa"],
    "user_016": ["falafel", "hummus", "shawarma", "kebab", "pita"],
    "user_017": ["pancakes", "waffle", "french_toast", "crepe", "granola"],
    "user_018": ["fish_tacos", "ceviche", "grilled_salmon", "sushi", "prawn_curry"],
    "user_019": ["burger", "hotdog", "fries", "onion_rings", "milkshake"],
    "user_020": ["dal", "sabzi", "roti", "biryani", "kheer"],
    "user_021": ["dim_sum", "dumplings", "fried_rice", "noodles", "peking_duck"],
    "user_022": ["croissant", "baguette", "quiche", "crepe", "macaroon"],
    "user_023": ["gelato", "tiramisu", "cannoli", "pizza", "risotto"],
    "user_024": ["nachos", "tacos", "burrito", "churros", "horchata"],
    "user_025": ["jollof_rice", "suya", "puff_puff", "egusi", "plantain"],
}

# restaurant_id -> restaurant details
RESTAURANTS = {
    "rest_001": {"name": "Pizza Palace",        "profile_image": "https://example.com/rest_001.jpg"},
    "rest_002": {"name": "Pasta Paradise",      "profile_image": "https://example.com/rest_002.jpg"},
    "rest_003": {"name": "Burger Barn",         "profile_image": "https://example.com/rest_003.jpg"},
    "rest_004": {"name": "Sushi Station",       "profile_image": "https://example.com/rest_004.jpg"},
    "rest_005": {"name": "Taco Town",           "profile_image": "https://example.com/rest_005.jpg"},
    "rest_006": {"name": "Biryani House",       "profile_image": "https://example.com/rest_006.jpg"},
    "rest_007": {"name": "Curry Corner",        "profile_image": "https://example.com/rest_007.jpg"},
    "rest_008": {"name": "Dosa Delight",        "profile_image": "https://example.com/rest_008.jpg"},
    "rest_009": {"name": "Green Bowl",          "profile_image": "https://example.com/rest_009.jpg"},
    "rest_010": {"name": "Steak House",         "profile_image": "https://example.com/rest_010.jpg"},
    "rest_011": {"name": "Ramen Republic",      "profile_image": "https://example.com/rest_011.jpg"},
    "rest_012": {"name": "Dumpling Den",        "profile_image": "https://example.com/rest_012.jpg"},
    "rest_013": {"name": "Nacho Nights",        "profile_image": "https://example.com/rest_013.jpg"},
    "rest_014": {"name": "Shawarma Street",     "profile_image": "https://example.com/rest_014.jpg"},
    "rest_015": {"name": "Waffle World",        "profile_image": "https://example.com/rest_015.jpg"},
}

# reel_id -> reel details
REELS = {
    "reel_001": {"category": "pizza",         "restaurant_id": "rest_001", "like_count": 120},
    "reel_002": {"category": "pizza",         "restaurant_id": "rest_001", "like_count": 95},
    "reel_003": {"category": "pasta",         "restaurant_id": "rest_002", "like_count": 80},
    "reel_004": {"category": "pasta",         "restaurant_id": "rest_002", "like_count": 60},
    "reel_005": {"category": "burgers",       "restaurant_id": "rest_003", "like_count": 200},
    "reel_006": {"category": "burgers",       "restaurant_id": "rest_003", "like_count": 175},
    "reel_007": {"category": "sushi",         "restaurant_id": "rest_004", "like_count": 300},
    "reel_008": {"category": "sushi",         "restaurant_id": "rest_004", "like_count": 250},
    "reel_009": {"category": "tacos",         "restaurant_id": "rest_005", "like_count": 90},
    "reel_010": {"category": "tacos",         "restaurant_id": "rest_005", "like_count": 110},
    "reel_011": {"category": "biryani",       "restaurant_id": "rest_006", "like_count": 400},
    "reel_012": {"category": "biryani",       "restaurant_id": "rest_006", "like_count": 380},
    "reel_013": {"category": "curry",         "restaurant_id": "rest_007", "like_count": 150},
    "reel_014": {"category": "butter_chicken","restaurant_id": "rest_007", "like_count": 220},
    "reel_015": {"category": "dosa",          "restaurant_id": "rest_008", "like_count": 130},
    "reel_016": {"category": "idli",          "restaurant_id": "rest_008", "like_count": 100},
    "reel_017": {"category": "salad",         "restaurant_id": "rest_009", "like_count": 75},
    "reel_018": {"category": "smoothie",      "restaurant_id": "rest_009", "like_count": 88},
    "reel_019": {"category": "avocado",       "restaurant_id": "rest_009", "like_count": 95},
    "reel_020": {"category": "steak",         "restaurant_id": "rest_010", "like_count": 500},
    "reel_021": {"category": "bbq",           "restaurant_id": "rest_010", "like_count": 430},
    "reel_022": {"category": "ribs",          "restaurant_id": "rest_010", "like_count": 390},
    "reel_023": {"category": "ramen",         "restaurant_id": "rest_011", "like_count": 270},
    "reel_024": {"category": "ramen",         "restaurant_id": "rest_011", "like_count": 310},
    "reel_025": {"category": "dumplings",     "restaurant_id": "rest_012", "like_count": 185},
    "reel_026": {"category": "pho",           "restaurant_id": "rest_011", "like_count": 160},
    "reel_027": {"category": "pad_thai",      "restaurant_id": "rest_011", "like_count": 140},
    "reel_028": {"category": "nachos",        "restaurant_id": "rest_013", "like_count": 210},
    "reel_029": {"category": "burrito",       "restaurant_id": "rest_013", "like_count": 195},
    "reel_030": {"category": "quesadilla",    "restaurant_id": "rest_013", "like_count": 170},
    "reel_031": {"category": "shawarma",      "restaurant_id": "rest_014", "like_count": 240},
    "reel_032": {"category": "falafel",       "restaurant_id": "rest_014", "like_count": 190},
    "reel_033": {"category": "hummus",        "restaurant_id": "rest_014", "like_count": 155},
    "reel_034": {"category": "waffle",        "restaurant_id": "rest_015", "like_count": 280},
    "reel_035": {"category": "pancakes",      "restaurant_id": "rest_015", "like_count": 260},
    "reel_036": {"category": "crepe",         "restaurant_id": "rest_015", "like_count": 230},
    "reel_037": {"category": "cheesecake",    "restaurant_id": "rest_015", "like_count": 320},
    "reel_038": {"category": "icecream",      "restaurant_id": "rest_015", "like_count": 410},
    "reel_039": {"category": "grilled_salmon","restaurant_id": "rest_004", "like_count": 175},
    "reel_040": {"category": "prawn_curry",   "restaurant_id": "rest_007", "like_count": 145},
    "reel_041": {"category": "fried_rice",    "restaurant_id": "rest_012", "like_count": 200},
    "reel_042": {"category": "noodles",       "restaurant_id": "rest_012", "like_count": 180},
    "reel_043": {"category": "dim_sum",       "restaurant_id": "rest_012", "like_count": 220},
    "reel_044": {"category": "risotto",       "restaurant_id": "rest_002", "like_count": 165},
    "reel_045": {"category": "tiramisu",      "restaurant_id": "rest_002", "like_count": 195},
    "reel_046": {"category": "jollof_rice",   "restaurant_id": "rest_006", "like_count": 300},
    "reel_047": {"category": "plantain",      "restaurant_id": "rest_006", "like_count": 275},
    "reel_048": {"category": "dal",           "restaurant_id": "rest_007", "like_count": 130},
    "reel_049": {"category": "paneer",        "restaurant_id": "rest_007", "like_count": 210},
    "reel_050": {"category": "kebab",         "restaurant_id": "rest_014", "like_count": 290},
}

# In-memory seen reels tracker: { user_id: set of reel_ids }
SEEN_REELS = {}

# In-memory likes tracker: { user_id: set of reel_ids they liked }
USER_LIKES = {}

# In-memory like count per category per user: { user_id: { category: count } }
USER_CATEGORY_LIKES = {}